version: "3.8"

services:
  app:
    # image: registry.digitalocean.com/fleettrack/test:latest
    image: asia-south1-docker.pkg.dev/gpstrack-2/fleettrack/test:latest
    environment:
      - TASK_ID={{.Task.Slot}}
    command: node server.js
    deploy:
      replicas: 2
      restart_policy: 
        condition: any
      # resources:
      #   limits:
      #     memory: 30M
      # placement:
        # constraints:
          # - node.role == worker
          # - node.labels.manager == yes

    expose:
      - 1800
    networks:
      - gpsnet

  nginx:
    image: nginx:latest
    restart: always
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    deploy:
      # restart_policy: 
      #   condition: any
      #   delay: 5s
      #   max_attempts: 3
      #   window: 120s
      # resources:
      #   limits:
      #     memory: 50M
    # deploy:
    #   restart_policy:
    #     condition: on-failure
    #   replicas: 1
    #   resources:
    #     limits:
    #       memory: 40M
    #     reservations:
    #       memory: 5M
      placement:
        constraints:
          - node.labels.lb == yes
    depends_on:
      - app 
    ports:
      - 1800:1800
    networks:
      - gpsnet

configs:
  nginx_config:
    file: ./nginx.conf
    
networks:
  gpsnet:
