version: '3.8'

services:
  web:
    image: registry.digitalocean.com/fleettrack-registry/gps:latest
#    ports:
#      - "1800:1800"
    deploy:
      replicas: 4
      placement:
        constraints:
          - node.labels.node-type == gps1 # Replace 'gps-server' with your actual node labels
  
    expose:
      - 1800  
    networks:
      - webnet

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.node-type == my-shell-droplet # Replace 'load-balancer' with your actual node labels
  
    ports:
      - 1800:1800
    depends_on:
      - web

networks:
  webnet:
