apiVersion: v1
kind: ConfigMap
metadata:
  name: 10-digitalocean.conflist
  namespace: kube-system
data:
  cni-conf.json: |
    {
      "name": "digitalocean",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "portmap",
          "capabilities": {"portMappings": true},
          "snat": true
        },
        {
          "type": "digitalocean",
          "mode": "insert",
          "useFloatingIPs": true
        },
      ]
    }
