apiVersion: apps/v1
kind: Deployment
metadata:
  name: gps
spec:
  replicas: 4
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: gps
  template:
    metadata:
      labels:
        app: gps
    spec:
      # affinity:
      #   nodeAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - weight: 60
      #       preference:
      #         matchExpressions:
      #         - key: gpstrack.in/16cpu
      #           operator: In
      #           values:
      #           - 'true'
      #     - weight: 40
      #       preference:
      #         matchExpressions:
      #         - key: gpstrack.in/32cpu
      #           operator: In
      #           values:
      #           - 'true'
      containers:
        - name: gps-container
          image: asia-south1-docker.pkg.dev/gpstrack-2/fleettrack/test:latest
          env:
            - name: TASK_ID
              value: "1"
          command: ["node", "server.js"]
          imagePullPolicy: Always
          # resources:
          #   requests:
          #     cpu: "0.1"
              # memory: "100Mi"
            # limits:
              # cpu: "2000m"
              # memory: "1200Mi"
          ports:
            - containerPort: 1800
      imagePullSecrets:
        - name: gcr-secret

