version: "3"
services:
  nginx:
    image: nginx:1.20.1
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      replicas: 1
      
    ports:
      - 1800:1800
      