apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: my-pool
      protocol: layer2
      addresses:
      - 144.126.255.213-144.126.255.213  # Specify your desired IP address
