apiVersion: v1
kind: Service
metadata:
  name: lb-gps
  # annotations:
  #   metallb.universe.tf/loadBalancerIPs: 144.126.255.213
  # annotations:
  #   metallb.universe.tf/allow-shared-ip: my-pool
spec:
  type: LoadBalancer
  # loadBalancerIP: 144.126.255.213
  # externalTrafficPolicy: Local
  selector:
    app: gps
  ports:
    - protocol: TCP
      port: 1800
      targetPort: 1800
      # nodePort: 31800
  externalIPs:
    - 144.126.255.213
    - 128.199.28.205

