apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gps
spec:
  replicas: 2
  podManagementPolicy: Parallel
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: gps
  template:
    metadata:
      labels:
        app: gps
    spec:
      containers:
        - name: gps-container
          image: asia-south1-docker.pkg.dev/gpstrack-2/fleettrack/test:latest
          env:
          # - name: TASK_ID
          #   value: "1"
          - name: TASK_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['apps.kubernetes.io/pod-index']

          command: ["node", "server.js"]
          resources:
            # requests:
            #   memory: "64Mi"
            #   cpu: "250m"
            limits:
              memory: "50Mi"
              # cpu: "500m"
          imagePullPolicy: Always
          ports:
            - containerPort: 1800
      imagePullSecrets:
        - name: gcr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: lb-gps
spec:
  type: LoadBalancer
  selector:
    app: gps
  ports:
    - protocol: TCP
      port: 1800
      targetPort: 1800
      # nodePort: 31800
  externalIPs:
    - 139.59.44.250
