version: '3.8'

services:
  
  nginx-lb:
    image: nginx:latest
    volumes:
      - ./lb-nginx.conf:/etc/nginx/nginx.conf
    deploy:
      replicas: 1
      placement:
        constraints:
          # - node.labels.node-type == my-shell-droplet
          # - node.hostname == my-shell-droplet
          - node.role == manager
  
    ports:
      - 1800:1800
