version: '3.7'

services:
  app:
    image: registry.digitalocean.com/fleettrack-registry/gps:latest
    # ports:
    #   - "1800:1800"
    deploy:
      replicas: 4
    networks:
      - my_network

  nginx:
    image: nginx:latest
    ports:
      - "1800:1800"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - my_network

networks:
  my_network:
