version: '3.8'

services:
  haproxy:
    image: haproxy:latest
    ports:
      - "1800:1800"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    deploy:
      replicas: 1
      placement:
        constraints:
          # - node.labels.node-type == my-shell-droplet
          # - node.hostname == my-shell-droplet
          - node.role == manager
    networks:
      - frontend
      - backend

  app:
    image: registry.digitalocean.com/fleettrack-registry/gps:latest
    deploy:
      replicas: 3
    expose:
      - 1800
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
